notifications:
  email: false

language: node_js
node_js:
  - 9
  - 8

sudo: required

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-tag-1.37.31-64bit bash

script:
  - docker exec -it emscripten emmake make
  - npm run test